version: "3"

services:
  db:
    image: mysql:5.7
    hostname: mysqlhost
    volumes:
      - /var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ciapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  ciapp:
    build: ./app
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    restart: always
    links:
      - db:mysql
    ports:
      - "8080:80"

volumes:
  db_data:
